version: '3'

services:
  nodejs:
    #fill out the configuration here
    image: node:10-alpine
    container_name: personal-website 
    command: node app.js
    networks:
      - app-network
  
  #the nginx configuration is given below
  #the website will run on localhost:80 
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "81:8080"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      #fill out your absolute path to your folder here
      device: /home/affanmalik/Year3/CMSC389T/p3
      o: bind

networks:
  app-network:
    driver: bridge 
